// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: selfmessage.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_selfmessage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_selfmessage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_selfmessage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_selfmessage_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_selfmessage_2eproto;
namespace bowpb {
class BowMsg;
class BowMsgDefaultTypeInternal;
extern BowMsgDefaultTypeInternal _BowMsg_default_instance_;
}  // namespace bowpb
PROTOBUF_NAMESPACE_OPEN
template<> ::bowpb::BowMsg* Arena::CreateMaybeMessage<::bowpb::BowMsg>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace bowpb {

// ===================================================================

class BowMsg :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:bowpb.BowMsg) */ {
 public:
  BowMsg();
  virtual ~BowMsg();

  BowMsg(const BowMsg& from);
  BowMsg(BowMsg&& from) noexcept
    : BowMsg() {
    *this = ::std::move(from);
  }

  inline BowMsg& operator=(const BowMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline BowMsg& operator=(BowMsg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const BowMsg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BowMsg* internal_default_instance() {
    return reinterpret_cast<const BowMsg*>(
               &_BowMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(BowMsg& a, BowMsg& b) {
    a.Swap(&b);
  }
  inline void Swap(BowMsg* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline BowMsg* New() const final {
    return CreateMaybeMessage<BowMsg>(nullptr);
  }

  BowMsg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<BowMsg>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const BowMsg& from);
  void MergeFrom(const BowMsg& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BowMsg* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "bowpb.BowMsg";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_selfmessage_2eproto);
    return ::descriptor_table_selfmessage_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTypeNameFieldNumber = 1,
    kMsgDataFieldNumber = 2,
  };
  // optional string type_name = 1;
  bool has_type_name() const;
  private:
  bool _internal_has_type_name() const;
  public:
  void clear_type_name();
  const std::string& type_name() const;
  void set_type_name(const std::string& value);
  void set_type_name(std::string&& value);
  void set_type_name(const char* value);
  void set_type_name(const char* value, size_t size);
  std::string* mutable_type_name();
  std::string* release_type_name();
  void set_allocated_type_name(std::string* type_name);
  private:
  const std::string& _internal_type_name() const;
  void _internal_set_type_name(const std::string& value);
  std::string* _internal_mutable_type_name();
  public:

  // optional bytes msg_data = 2;
  bool has_msg_data() const;
  private:
  bool _internal_has_msg_data() const;
  public:
  void clear_msg_data();
  const std::string& msg_data() const;
  void set_msg_data(const std::string& value);
  void set_msg_data(std::string&& value);
  void set_msg_data(const char* value);
  void set_msg_data(const void* value, size_t size);
  std::string* mutable_msg_data();
  std::string* release_msg_data();
  void set_allocated_msg_data(std::string* msg_data);
  private:
  const std::string& _internal_msg_data() const;
  void _internal_set_msg_data(const std::string& value);
  std::string* _internal_mutable_msg_data();
  public:

  // @@protoc_insertion_point(class_scope:bowpb.BowMsg)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr type_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr msg_data_;
  friend struct ::TableStruct_selfmessage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BowMsg

// optional string type_name = 1;
inline bool BowMsg::_internal_has_type_name() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool BowMsg::has_type_name() const {
  return _internal_has_type_name();
}
inline void BowMsg::clear_type_name() {
  type_name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& BowMsg::type_name() const {
  // @@protoc_insertion_point(field_get:bowpb.BowMsg.type_name)
  return _internal_type_name();
}
inline void BowMsg::set_type_name(const std::string& value) {
  _internal_set_type_name(value);
  // @@protoc_insertion_point(field_set:bowpb.BowMsg.type_name)
}
inline std::string* BowMsg::mutable_type_name() {
  // @@protoc_insertion_point(field_mutable:bowpb.BowMsg.type_name)
  return _internal_mutable_type_name();
}
inline const std::string& BowMsg::_internal_type_name() const {
  return type_name_.GetNoArena();
}
inline void BowMsg::_internal_set_type_name(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  type_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void BowMsg::set_type_name(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  type_name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:bowpb.BowMsg.type_name)
}
inline void BowMsg::set_type_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  type_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bowpb.BowMsg.type_name)
}
inline void BowMsg::set_type_name(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  type_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bowpb.BowMsg.type_name)
}
inline std::string* BowMsg::_internal_mutable_type_name() {
  _has_bits_[0] |= 0x00000001u;
  return type_name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* BowMsg::release_type_name() {
  // @@protoc_insertion_point(field_release:bowpb.BowMsg.type_name)
  if (!_internal_has_type_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return type_name_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void BowMsg::set_allocated_type_name(std::string* type_name) {
  if (type_name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  type_name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), type_name);
  // @@protoc_insertion_point(field_set_allocated:bowpb.BowMsg.type_name)
}

// optional bytes msg_data = 2;
inline bool BowMsg::_internal_has_msg_data() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool BowMsg::has_msg_data() const {
  return _internal_has_msg_data();
}
inline void BowMsg::clear_msg_data() {
  msg_data_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& BowMsg::msg_data() const {
  // @@protoc_insertion_point(field_get:bowpb.BowMsg.msg_data)
  return _internal_msg_data();
}
inline void BowMsg::set_msg_data(const std::string& value) {
  _internal_set_msg_data(value);
  // @@protoc_insertion_point(field_set:bowpb.BowMsg.msg_data)
}
inline std::string* BowMsg::mutable_msg_data() {
  // @@protoc_insertion_point(field_mutable:bowpb.BowMsg.msg_data)
  return _internal_mutable_msg_data();
}
inline const std::string& BowMsg::_internal_msg_data() const {
  return msg_data_.GetNoArena();
}
inline void BowMsg::_internal_set_msg_data(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  msg_data_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void BowMsg::set_msg_data(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  msg_data_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:bowpb.BowMsg.msg_data)
}
inline void BowMsg::set_msg_data(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  msg_data_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bowpb.BowMsg.msg_data)
}
inline void BowMsg::set_msg_data(const void* value, size_t size) {
  _has_bits_[0] |= 0x00000002u;
  msg_data_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bowpb.BowMsg.msg_data)
}
inline std::string* BowMsg::_internal_mutable_msg_data() {
  _has_bits_[0] |= 0x00000002u;
  return msg_data_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* BowMsg::release_msg_data() {
  // @@protoc_insertion_point(field_release:bowpb.BowMsg.msg_data)
  if (!_internal_has_msg_data()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return msg_data_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void BowMsg::set_allocated_msg_data(std::string* msg_data) {
  if (msg_data != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  msg_data_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), msg_data);
  // @@protoc_insertion_point(field_set_allocated:bowpb.BowMsg.msg_data)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace bowpb

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_selfmessage_2eproto
